version: '2'

services:
  # Our mysql service:
  mysql:
    image: mysql:latest ################
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  rabbitmq:
    image: rabbitmq:3.6.9-alpine
    restart: always
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq

  es:
    image: elasticsearch:5.4.0-alpine
    restart: always
    ports:
      - "9300:9200"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data

  web:
    build: .
    command: sh -c "sh wait-curl.sh es:9200 && sh ./init.sh && rails s -p 3000 -b '0.0.0.0'"
    restart: always
    ports:
      - "4000:3000"
    links:
      - mysql
      - es
      - rabbitmq
    environment:
      - MYSQL_HOST=mysql
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es

  worker:
    build: .
    command: sh -c "sh wait-curl.sh es:9200 && rails sneakers:run"
    restart: always
    volumes:
      - .:/app
    links:
      - mysql
      - es
      - rabbitmq
    depends_on:
      - web
    environment:
      - WORKERS=ApplicationsWorkers
      - MYSQL_HOST=mysql
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es